require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Configure email delivery: use SMTP (e.g. Mailpit) if SMTP_ADDRESS is present, otherwise letter_opener
  if ENV["SMTP_ADDRESS"].present?
    config.action_mailer.delivery_method = :smtp
    config.action_mailer.smtp_settings = {
      address:              ENV["SMTP_ADDRESS"],
      port:                 ENV.fetch("SMTP_PORT", 1025).to_i,
      domain:               ENV.fetch("SMTP_DOMAIN", "localhost"),
      user_name:            ENV["SMTP_USER_NAME"].presence,
      password:             ENV["SMTP_PASSWORD"].presence,
      authentication:       ENV["SMTP_AUTHENTICATION"].presence,
      enable_starttls_auto: ENV["SMTP_ENABLE_STARTTLS_AUTO"] == "true"
    }
  else
    config.action_mailer.delivery_method = :letter_opener
    LetterOpener.configure do |config|
      config.location = Rails.root.join("tmp/letter_opener")
    end
  end

  # Set host, port, and protocol to be used by links generated in mailer templates and route helpers.
  app_host = ENV.fetch("APP_HOST", "localhost")
  app_protocol = ENV.fetch("APP_PROTOCOL", "http")
  app_port = ENV["APP_PORT"].presence

  if app_protocol == "https"
    url_port = nil
  else
    url_port = app_port ? app_port.to_i : nil
  end

  config.action_mailer.default_url_options = {
    host: app_host,
    protocol: app_protocol,
    port: url_port
  }.compact

  # Set host and options for route helpers (ActiveStorage URLs, etc.)
  Rails.application.routes.default_url_options[:host] = app_host
  Rails.application.routes.default_url_options[:protocol] = app_protocol
  Rails.application.routes.default_url_options[:port] = url_port if url_port

  # Allow the application to receive requests on the configured APP_HOST and its subdomains.
  if ENV["APP_HOST"].present?
    config.hosts << ENV["APP_HOST"]
    config.hosts << ".#{ENV["APP_HOST"]}"
    config.hosts << ".#{SatuRayaIdentityClient::Identity::BrandConfig.app_domain}"
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Allow Action Cable connections from the configured app host under SSL proxy
  domain = SatuRayaIdentityClient::Identity::BrandConfig.app_domain
  domain_regex = /https?:\/\/.*\.#{Regexp.escape(domain)}/

  config.action_cable.allowed_request_origins = [
    "https://#{ENV.fetch('APP_HOST', domain)}",
    "http://#{ENV.fetch('APP_HOST', domain)}",
    domain_regex,
    /https?:\/\/localhost:\d+/
  ]

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!

  # Use solid_queue for background jobs
  config.active_job.queue_adapter = :solid_queue

  # Performance audit with Bullet
  config.after_initialize do
    Bullet.enable = true
    Bullet.alert = true
    Bullet.bullet_logger = true
    Bullet.console = true
    Bullet.rails_logger = true
    Bullet.add_footer = true

    # Whitelist Active Storage's internal associations to avoid false positive warnings
    Bullet.add_safelist type: :unused_eager_loading, class_name: "ActiveStorage::Attachment", association: :record
  end

  # Fallback credentials for ActiveRecord encryption in development environment
  config.active_record.encryption.primary_key = "a" * 32
  config.active_record.encryption.deterministic_key = "b" * 32
  config.active_record.encryption.key_derivation_salt = "c" * 32
end
