FROM satu-raya-app:dev-v1.0

ENV RAILS_ENV="test"

# Install Node.js, npm, and chromium dependencies
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    curl \
    gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y --no-install-recommends \
    nodejs \
    libgbm1 \
    libnss3 \
    libnspr4 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxkbcommon0 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libasound2 \
    libpango-1.0-0 \
    libcairo2 \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Pre-install playwright browser driver and Chromium browser
RUN npm install -g playwright && npx playwright install-deps chromium && npx playwright install chromium
